package ExceptionPkg;

public class exceptionDemo {

	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		exceptionDemo obj=new exceptionDemo();
		int i=4;
		int b=7;
		//int c=0;
		
		try {
		//int k=b/c;
		
		String str1="Arun";
	
		//System.out.println(k);
		// System.out.println(str1.charAt(5));
		str1=null;
		System.out.println(str1.length());
		
		}
		catch(ArithmeticException ate) {
			System.out.println("ArithmeticException Error : "+ate);
		}
		catch(IndexOutOfBoundsException iobe) {
			System.out.println("Index Out of Range Error - "+iobe);
			
		}
		catch(NullPointerException ne) {
			System.out.println("str1 value is NULL, throwing NULL Pointer error - "+ne);
		}
		catch(Exception e) {
			System.out.println("c value is zero, user can devide value with zero "+e);
		}
		
	}

}
